services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        USERNAME: dev
        USER_UID: "1000"
        USER_GID: "1000"
    volumes:
      - ..:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    command: sleep infinity
