services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        USERNAME: dev
        USER_UID: "1000"
        USER_GID: "1000"
    volumes:
      - ..:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
      - ${HOME}/.ssh:/home/dev/.ssh:ro
    environment:
      - DISPLAY=${DISPLAY}
      - SSH_AUTH_SOCK=/ssh-agent
    network_mode: host
    stdin_open: true
    tty: true
    command: sleep infinity
